name: themovers
description: "The Movers Online"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.3+32

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.2.0
  flutter_screenutil: ^5.9.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.0
  intl: ^0.18.1
  geolocator: ^9.0.2
  google_places_flutter: ^2.0.6
  google_maps_flutter: ^2.4.0
  flutter_polyline_points_plus: ^3.0.0
  image_picker: ^1.0.2
  timeline_tile: ^2.0.0
  firebase_core: ^2.19.0
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  firebase_auth: ^4.9.0
  action_slider: ^0.7.0
  intl_phone_field: ^3.2.0
  flutter_rating_bar: ^4.0.1
  country_code_picker: ^3.0.0
  carousel_slider: ^4.2.1
  modal_bottom_sheet: ^2.1.2
  flutter_svg: ^2.0.7
  dotted_line: ^3.2.2
  url_launcher: ^6.1.14
  flutter_spinkit: ^5.2.0
  facebook_app_events: ^0.19.0
  upgrader: ^8.4.0
  gif: ^2.3.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^4.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf

